config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end
  scope module: :public do
      devise_for :users
    root to: "homes#top"
    resources :post_images do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :index, :update, :destroy] do
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :body, presence: true
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [post_image, comment] do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <%= f.text_area :body, rows:'5', placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信" %>
<% end %>

app/views/comments/_index.html.erb
<table>
  <tbody>
    <% post_image.comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to user_path(comment.user) do %>
          <%= image_tag comment.user.get_profile_image(50,50) %><br>
          <%= comment.user.name %>
        <% end %>
      </td>
      <td><%= comment.body %></td>
      <td>
        <% if comment.user == current_user %>
          <%= link_to "Destroy", post_image_comment_path(post_image, comment), method: :delete, class: "btn btn-sm btn-danger float-end" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>