config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end
  scope module: :public do
      devise_for :users
    root to: "homes#top"
    resources :post_images do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :index, :update, :destroy] do
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @post_images = PostImage.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(50, 50) %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがPost_imageの時) -->
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>body</th>

      </tr>
    <tbody>
    <h2>Post_image search for "<%= @word %>"</h2>
    <% @post_images.each do |post_image| %>
      <tr>
        <td>
          <%= link_to user_path(post_image.user) do %>
            <%= image_tag post_image.user.get_profile_image(50, 50) %>
          <% end %>
        </td>
        <td><%= link_to post_image.title , post_image_path(post_image.id) %></td>
        <td><%= post_image.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>