config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end
  scope module: :public do
      devise_for :users
    root to: "homes#top"
    resources :post_images do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :index, :update, :destroy] do
      resources :favorites, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :name, presence:  true

  has_many :post_images, dependent: :destroy

  has_one_attached :profile_image

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

   # フォローしている関連付け
   has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    
   # フォローされている関連付け
   has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   # フォローしているユーザーを取得
   has_many :followings, through: :active_relationships, source: :followed
   
   # フォロワーを取得
   has_many :followers, through: :passive_relationships, source: :follower

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  
    # 指定したユーザーをフォローする
    def follow(user)
      active_relationships.create(followed_id: user.id)
    end
    
    # 指定したユーザーのフォローを解除する
    def unfollow(user)
      active_relationships.find_by(followed_id: user.id).destroy
    end
    
    # 指定したユーザーをフォローしているかどうかを判定
    def following?(user)
      followings.include?(user)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
    end

    def show
        @user = User.find(params[:id])
        @post_images = @user.post_images.page(params[:page])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <%= link_to '退会', admin_user_path(@user), method: :delete, data: { confirm: '本当に削除しますか？' } %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>画像</th>
      <th>観光地名</th>
      <th>投稿ユーザー画像</th>
      <th>ユーザーネーム</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @post_images.each do |post_image| %>
      <tr>
        <td>
          <%= link_to post_image_path(post_image.id) do %>
            <%= image_tag post_image.get_image(100,100) %>
          <% end %>
        </td>
        <td><%= post_image.title %></td>
        <td><%= image_tag post_image.user.get_profile_image(100,100) %></td>
        <td><%= post_image.user.name %></td>
        <td>コメント数： <%= post_image.comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
  <%= paginate @post_images %>
</div>